-- a.Faça os scripts para a criação das tabelas, sem as constraints;

CREATE TABLE CUSTUMER(
    NMCUSTOMER VARCHAR(50),
    NRFONE VARCHAR(15),
    DSADRESS VARCHAR(100)
);

CREATE TABLE REQUEST(
    DTREQUEST DATE,
    DTDELIVER DATE,
    VLTOTAL MONEY,
    CDCUSTOMER INT
);

CREATE TABLE PRODUCTREQUEST(
    CDREQUEST INT,
    CDPRODUCT INT,
    QTAMOUNT INT,
    VLUNITARY MONEY,
    PRIMARY KEY (CDREQUEST, CDPRODUCT)
);

CREATE TABLE PRODUCT(
    NMPRODUCT INT,
    VLPRICE MONEY,
    QTSTOCK INT,
    CDSUPPLIER INT
);

CREATE TABLE SUPPLIER(NMSUPPLIER INT, NRFONE VARCHAR(15));