-- c. Faça os scripts para a criação das chaves secundárias das tabelas criadas;

ALTER TABLE REQUEST
ADD CONSTRAINT FK_CDCUSTOMER
FOREIGN KEY (CDCUSTOMER) REFERENCES CUSTUMER(CDCUSTOMER);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_CDSUPPLIER
FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER(CDSUPPLIER);